VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos/6"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
  end

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  config.vm.box_check_update = false

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network :private_network, ip: "192.168.60.159"

  config.vm.network "forwarded_port", guest: 80, host: 1234, auto_correct: true
  config.vm.network "forwarded_port", guest: 3306, host: 1235, auto_correct: true

  config.vm.synced_folder "./", "/vagrant", owner: 'vagrant', group: 'vagrant', mount_options: ["dmode=777", "fmode=777"], type: 'virtualbox'

  # config.vm.provision "shell", path: "scripts/scripts.sh"
  # Auto start httpd after vagrant mount folder
  config.vm.provision :shell, :inline => "sudo service httpd start; sudo setenforce 0;", run: "always"
end
